<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerScB1sv9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerScB1sv9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerScB1sv9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerScB1sv9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerScB1sv9\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ScB1sv9',
    'container.build_id' => '2c6a228f',
    'container.build_time' => 1536024482,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerScB1sv9');
