<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Perfil\PerfilController' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\Perfil\\PerfilController.php';

return $this->services['App\Controller\Perfil\PerfilController'] = new \App\Controller\Perfil\PerfilController();
